version: "3.9"

services:
  database:
    image: "mysql:5.7"
    ports:
      - 3306
    env_file:
      - secrets.yaml
  guestbook:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    volumes:
      - ./guestbook:/app/guestbook
    environment:
      FLASK_ENV: development
      LOG_LEVEL: "DEBUG"
    ports:
      - "9000:9000"
    env_file:
      - secrets.yaml
    depends_on:
      - database