version: "3.9"

services:
  database:
    image: "mysql:5.7"
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: guestbook
      MYSQL_USER: guestbook
      MYSQL_PASSWORD: abc123
    env_file:
      - secrets.yaml

  guestbook:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    volumes:
      - ./guestbook:/app/guestbook
    environment:
      FLASK_ENV: development
      LOG_LEVEL: "DEBUG"
      MYSQL_HOST: "database"
      MYSQL_USER: "root"
    ports:
      - "9000:9000"
    env_file:
      - secrets.yaml
    depends_on:
      - database