version: "3.9"

services:
  database:
    image: "mysql:5.7"
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "abc123"
    env_file:
      - secrets.env
  guestbook:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: development
      LOG_LEVEL: "DEBUG"
    ports:
      - "5000:9500"
    env_file:
      - secrets.env
    depends_on:
      - database