releases:
  - name: "myapp"
    chart: "deploy/"
    namespace: myapp
    createNamespace: true
environments:
  prod:
    kubeContext: kubernetes-admin@kubernetes
    values:
      - values-prod.yaml
    secrets:
      - secrets-prod.yaml
  dev:
    kubeContext: gke_myapp-341118_europe-west4_myappcluster
    values:
      - values-dev.yaml
    secrets:
      - secrets-dev.yaml