releases:
  - name: "myapp"
    chart: "deploy/"
    namespace: myapp
    createNamespace: true
    values:
      - values-{{ .Environment.Name }}.yaml
    secrets:
      - secrets-{{ .Environment.Name }}.yaml
environments:
  prod:
    kubeContext: kubernetes-admin@kubernetes
  dev:
    kubeContext: gke_myapp-341118_europe-west4_myappcluster