repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: "myapp"
    chart: "deploy/"
    namespace: myapp
    createNamespace: true
    values:
      - values-shared.yaml
      - values-{{ .Environment.Name }}.yaml
    secrets:
      - secrets-{{ .Environment.Name }}.yaml
  - name: mysql
    namespace: myapp
    createNamespace: true
    chart: bitnami/mysql
    values:
      - values-mysql-shared.yaml
    secrets:
      - secrets-{{ .Environment.Name }}.yaml
environments:
  prod:
    kubeContext: gke_myapp-341118_europe-west4_prod-cluster
  dev:
    kubeContext: gke_myapp-341118_europe-west4_myappcluster
