---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: artifactcred
data:
  .dockerconfigjson: {{ .Values.DOCKER_AUTH | b64enc | quote }}
type: kubernetes.io/dockerconfigjson