---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ .Values.mysql_secret_name }}
data:
  mysql_password: {{ .Values.MYSQL_USER_PASSWORD | b64enc | quote }}
  mysql_user: {{ .Values.MYSQL_USER | b64enc | quote }}
  