apiVersion: monitoring.googleapis.com/v1alpha1
kind: PodMonitoring
metadata:
  name: prom-collector
spec:
  selector:
    matchLabels:
      {{ include "deploy.selectorLabels" . | nindent 8 }}
  endpoints:
  - port: http
    path: /metrics
    scheme: http

    # (1) scrape metrics less frequently than the default (once every 60s)
    interval: 30s
