"""empty message

Revision ID: e40193d8e510
Revises: 
Create Date: 2022-02-11 23:54:49.576544

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e40193d8e510"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("book_name", sa.String(length=64), nullable=True),
        sa.Column("review", sa.Text(length=1024), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("password", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_table("reviews")
    # ### end Alembic commands ###
